### ISSUE TITLE
When will training codes be available?

### ISSUE THREAD

**Issue by bityangke** [tzzcl/PSOL#1]
Hi Chenlin,
Thanks for sharing your great work. When will you release the training codes, I am looking forward to it.
Thanks!

**Comment by tzzcl** [comment]
Hi, Thank you for your interest in our work!

I'm now busying with some projects simultaneously, one of these projects is the extension of our PSOL tasks. I think I will finish the code cleaning work and upload the code before the end of July.

**Comment by bityangke** [comment]
Thanks for your reply.  Looking forward to it.

**Comment by tzzcl** [comment]
> Thanks for your reply. Looking forward to it.

Hi, I just uploaded the code for training our PSOL on ImageNet, please check it!
