### ISSUE TITLE
请问pytorch和python是那个版本

### ISSUE THREAD

**Issue by joe660** [tzzcl/PSOL#14]
请问您论文中pytorch和python是那个版本？谢谢

**Comment by tzzcl** [comment]
Python 3.6+, PyTorch 1.1+均可。

**Comment by joe660** [comment]
我是做医学图像检测的，我自己的数据集只有一类，可以使用您提出的方法吗？谢谢。



---原始邮件---
发件人: "Chen-Lin ***@***.***&gt;
发送时间: 2021年6月28日(周一) 晚上11:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tzzcl/PSOL] 请问pytorch和python是那个版本 (#14)




 
Python 3.6+, PyTorch 1.1+均可。

**Comment by tzzcl** [comment]
可以先使用DDT方法，生成伪标记框，DDT方法可参见：https://github.com/tzzcl/DDT。然后使用PSOL进行训练。
但医学图像与普通图像差异较大，直接应用此方法可能不会好

**Comment by joe660** [comment]
> 可以先使用DDT方法，生成伪标记框，DDT方法可参见：[https://github.com/tzzcl/DDT。然后使用PSOL进行训练。](https://github.com/tzzcl/DDT%E3%80%82%E7%84%B6%E5%90%8E%E4%BD%BF%E7%94%A8PSOL%E8%BF%9B%E8%A1%8C%E8%AE%AD%E7%BB%83%E3%80%82)
> 但医学图像与普通图像差异较大，直接应用此方法可能不会好

作者 这个DDT的连接失效了   您有新的可以发给我吗？谢谢！

**Comment by joe660** [comment]
> 可以先使用DDT方法，生成伪标记框，DDT方法可参见：[https://github.com/tzzcl/DDT。然后使用PSOL进行训练。](https://github.com/tzzcl/DDT%E3%80%82%E7%84%B6%E5%90%8E%E4%BD%BF%E7%94%A8PSOL%E8%BF%9B%E8%A1%8C%E8%AE%AD%E7%BB%83%E3%80%82)
> 但医学图像与普通图像差异较大，直接应用此方法可能不会好

您是觉得医学图像相比自然图像中目标和背景太像，是这样效果可能会不好的吗？还是其他原因呢？
