### ISSUE TITLE
about val dataset

### ISSUE THREAD

**Issue by yumingfan-0219** [tzzcl/PSOL#16]
您好！ILSVRC的验证集具有50000个没有类别标签的图像，请问我应当如何将这些图像组织成readme中描述的格式：“val/class1,2,3,4.../image”？感谢您的回复！

**Comment by tzzcl** [comment]
ILSVRC上，验证集是有类别的，测试集上的数据才没有类别。

至于如何组织数据，可以参见PyTorch训练ImageNet的官方脚本：

https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh

**Comment by yumingfan-0219** [comment]
您的链接很好地解决了我的问题
感谢您如此快的回复！祝您科研之路一帆风顺
