### ISSUE TITLE
关于贵论文ten_crop的疑问

### ISSUE THREAD

**Issue by ustcjinggg** [tzzcl/PSOL#18]
请问在论文report的数据中，是否所有模型都使用了ten_crop? 还是VGG使用了ten_crop而ResNet没有用？

我比较好奇的是用ten_crop来提升分类的精度是否是所有模型分类通用做法？我看到的一些分类问题使用ResNet的时候并没有用ten_crop。比如ResNet50在ImageNet分类里达到76.2的Top1精度，是没有用ten_crop的？

**Comment by tzzcl** [comment]
你好，使用Ten Crop的做法一般在较早的模型中如VGG，InceptionV3会进行应用（为了提高分类准确率）。而在较近代的模型如ResNet中，大家一般就不使用Ten Crop了。在本文中，我们为了保持与之前WSOL文章的设置一样，对所有分类模型使用了Ten Crop。
但，ResNet50使用single-crop与ten-crop差距不大，Single Crop是76.2（76.15）。Ten Crop大概是76.6-76.7左右。

**Comment by ustcjinggg** [comment]
原来如此，感谢你的回答！
