### ISSUE TITLE
CUB_test_acc

### ISSUE THREAD

**Issue by chi0612** [tzzcl/PSOL#20]
我在CUB数据集上运行了您的train文件 在训练集可以达到90+的loc acc 但是测试集只有20左右的loc acc 请问这是什么
[out_CUB_vgg.log](https://github.com/tzzcl/PSOL/files/7657321/out_CUB_vgg.log)
原因

**Comment by tzzcl** [comment]
你好，根据你的Log，感觉是没有在CUB上训练好。建议看一下Label的组织是否正确，以及网络的初始化/学习率等参数。
