### ISSUE TITLE
Why do I use this PSOL_inference.py directly to get the accuracy rate is always 0 ？Do you have this problem？

### ISSUE THREAD

**Issue by xixiobba** [tzzcl/PSOL#5]
![image](https://user-images.githubusercontent.com/48711497/93091846-3d951680-f6d1-11ea-83c0-12192bb885c4.png)
my xml folder
![image](https://user-images.githubusercontent.com/48711497/93092061-88af2980-f6d1-11ea-8a74-ca3572def58c.png)
and i use your vgg16loc.pth.tar

**Comment by tzzcl** [comment]
As your comment, I think there is some problem in the localization weight loading stage, do you just use the default parameters? or you changed some line in the code?

By the way, you can use email to ask me more details:

my email is zclnjucs AT gmail.com,

Thanks!

**Comment by tzzcl** [comment]
I've changed the default loading parameter style in PSOL_inference.py, problem solved.

**Comment by Shiven004** [comment]
Hi Zhang,

For testing -python PSOL_inference.py --loc-model {$LOC_MODEL} --cls-model {$CLS_MODEL} {--ten-crop}
I am using this cmd- _`python PSOL_inference.py  --loc-model vgg16 --cls-model vgg16 {--ten-crop}`_

How to specify path of the model in this ?Getting this error:
**FileNotFoundError: [Errno 2] No such file or directory: 'vgg16loc.pth.tar'**
