### ISSUE TITLE
cache_groundtruth.mat file not found in PSOL Github repository!!!!

### ISSUE THREAD

**Issue by Shiven004** [tzzcl/PSOL#8]
Hi Zhang,

In **imagenet_loader.py** there is a function

```
def load_val_bbox(label_dict,all_imgs,gt_location):
      .........................
     import scipy.io as sio
      gt_label = sio.loadmat(os.path.join(gt_location,'cache_groundtruth.mat'))
      ..........................
```
Could you please share this file at _shivenderkhajuria@gmail.com_?

Thanks,
Shiven

**Comment by tzzcl** [comment]
Same to #2

**Comment by Shiven004** [comment]
Thanks Zhang for such a swift response.Appreciate it!!!

**Comment by Shiven004** [comment]
Hi Zhang,

For testing -python PSOL_inference.py --loc-model {$LOC_MODEL} --cls-model {$CLS_MODEL} {--ten-crop}
I am using this cmd- python PSOL_inference.py --loc-model vgg16 --cls-model vgg16 {--ten-crop}

How to specify path of the model in this ?Getting this error:
FileNotFoundError: [Errno 2] No such file or directory: 'vgg16loc.pth.tar'
